### ISSUE TITLE
文生图样例image: unknown format图片保存到桌面失败

### ISSUE THREAD

**Issue by delete-cloud** [devinyf/dashscopego#6]
<img width="398" alt="image" src="https://github.com/devinyf/dashscopego/assets/76783546/d8fc8d9d-88f1-423d-809e-35220aad6ac3"> 

Go version: go1.22.2 darwin/arm64  
OS: macOS Ventura 13.6.7  

阿里云控制台内查询到token额度有被消耗，但程序输出image: unknown format，在saveImg2Desktop()内部打印img显示为nil，google后发现可能是image.Decode或io的问题

第一次发issue，如有问题还请多多包涵并指出

**Comment by devinyf** [comment]
不好意思， 是我上次更新的时候添加了一个下载的参数， 忘记更新案例了:
在request 中添加 Download = true 就可以了, 
默认是不下载的， 可以从 `blob.ImgURL` 中的到图片链接
后续我会更新这个 example
谢谢

```golang
	req := &wanx.ImageSynthesisRequest{
		// Model: "wanx-v1",
		Model: model,
		Input: wanx.ImageSynthesisInput{
			Prompt: "A beautiful sunset",
		},
		Params: wanx.ImageSynthesisParams{
			N: 1,
		},
		Download: true, #  *增加这个参数*
	}
```

**Comment by delete-cloud** [comment]
感谢，已解决
