### ISSUE TITLE
有考虑接入到langchaingo里面去吗？[https://github.com/tmc/langchaingo]

### ISSUE THREAD

**Issue by 1347027216** [devinyf/dashscopego#7]

**Comment by devinyf** [comment]
有做这方面尝试:
https://github.com/devinyf/langchaingo

可以切换到 qwen_llm 功能分支试用
```sh
git checkout qwen_llm
```

当时发现 langchiango 项目经常出现 breaking change, 好像还不太稳定 所以暂时停更了

另外 dashscope 的模型插件功能, 还没想好怎么适配到 langcchian 这种 agent 中使用... 考虑封装成 tools， 但实际用起来效果不是太理想

**Comment by 1347027216** [comment]
好的，期待ing
