### ISSUE TITLE
Allow to change the DashScopeBaseURL to support international version

### ISSUE THREAD

**Issue by carlos-vorto** [devinyf/dashscopego#8]
There is another endpoint to access DashScope api using the internaltional version:
https://dashscope-intl.aliyuncs.com/api/v1/services/aigc/text-generation/generation

Currently its not possible to edit this. 

https://www.alibabacloud.com/help/en/model-studio/developer-reference/model-calling-in-sub-workspace

**Comment by devinyf** [comment]
Add a new client, try to use `NewTongyiClientIntl` instead of  `NewTongyiClient` 
```go
// cli := dashscopego.NewTongyiClient(model, token)
cli := dashscopego.NewTongyiClientIntl(model, token)
```

Hope this helps, Thanks.
