### ISSUE TITLE
AsyncTaskRequest 支持 Parameters 参数

### ISSUE THREAD

**Issue by holys** [devinyf/dashscopego#9]
按阿里云的文档，https://help.aliyun.com/zh/model-studio/developer-reference/paraformer-api?spm=a2c4g.11186623.0.0.1ccc14fcWBVMBF#b7791ba0d2gv1

是支持其他扩展参数的，比如 disfluency_removal_enabled ，希望大佬有空支持下

**Comment by devinyf** [comment]
暂时先添加了 disfluency_removal_enabled 和 language_hints 这两个参数
```golang
	payload := paraformer.PayloadIn{
		Parameters: paraformer.Parameters{
			SampleRate: 16000,
			Format:     "pcm",
			DisfluencyRemovalEnabled: true,      // 新增
			LanguageHints: []string{"zh", "en"}, // 新增
		},
                ... ...
	}
```
文档不是很详细， 还有一些其它的参数目前没看明白具体的用法...

**Comment by holys** [comment]
嗯是的，文档不全

**Comment by devinyf** [comment]
Close this issue alongside the merging of PR #10.
